#!/usr/bin/env python

import sys

from dyros_jet_gui_ch.task_control_relative import *
from rqt_gui.main import Main

plugin = 'dyros_jet_gui_ch'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))